name: Build CV and publish to gh-pages
on:
  push:
    branches:
      - main
env:
  LASTNAME: Shikibu
  AUTHOR: 'Shikibu, M.'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true
    - name: Generate Markdown References
      run: |
        quarto render sources/ref.qmd --to=md
        mv sources/ref_output.md outputs/ref_output.md
        python scripts/ref_edit.py '${{ env.AUTHOR }}'
    - name: Generate PDF CV
      run: |
        tlmgr install academicons ifplatform catchfile xurl
        quarto render main.qmd --to=pdf
        quarto render main.qmd --to=pdf
        mv main.pdf outputs/${{ env.LASTNAME }}_CV.pdf
    - name: Generate DOCX CV
      run: |
        quarto render main.qmd --to=docx
        mv main.docx outputs/${{ env.LASTNAME }}_CV.docx
    - name: Generate Markdown CV
      run: |
        quarto render main.qmd --to=md
          mv main.md outputs/${{ env.LASTNAME }}_CV.md
    - name: Upload dist folder
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: outputs/*
  deploy:
    name: Deploy to gh-pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Download dist folder
        uses: actions/download-artifact@v2
        with:
          name: "dist"
          path: dist
      - name: "Deploy!"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
